name: leo_rigging_dashboard
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  pinput: ^5.0.1
  flutter_svg: ^2.1.0
  get: ^4.7.2
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  image: ^4.5.4
  syncfusion_flutter_charts: ^29.1.41
  syncfusion_flutter_maps: ^29.1.41
  shared_preferences: ^2.5.3
  path_provider: ^2.1.1
  crop_your_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
     - assets/font/
     - assets/icon/
     - assets/images/
     - assets/jsons/
     - .env

  fonts:
     - family: Urbanist
       fonts:
         - asset: assets/font/Urbanist-Bold.ttf
         - asset: assets/font/Urbanist-Medium.ttf
         - asset: assets/font/Urbanist-Regular.ttf
         - asset: assets/font/Urbanist-SemiBold.ttf
